build:
  image: dongraham/node:devtool
  commands:
    - pwd
    - ls -la
    #
    # - npm -g install yarn
    # - cp /root/.ci/Dockerfile /drone
    # - mkdir -p /drone/data
    # - cp -rf /root/webapp/* /drone/data
    # - cd /drone/data
    # - yarn install > /dev/null

# publish:
#   docker:
#     username: $$DOCKER_HUB_USERNAME
#     password: $$DOCKER_HUB_PASSWORD
#     email: $$DOCKER_HUB_EMAIL
#     repo: dongraham/drone-express
#     tag: latest
#     file: Dockerfile.drone
#     context: /                       # context - the context path to use, defaults to root of the git repo
#     build_args:
#       - GIT_URL=$$DRONE_REPO
#       - GIT_COMMIT_HASH=$$DRONE_COMMIT
#   when:
#     branch: master
