---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: dongraham/node
    tag: 'devtool'

inputs:
- name: src

outputs:
- name: build

run:
  path: src/.ci/tasks/build.sh
