---
resources:
- name: src
  type: git
  source:
    uri: https://github.com/donovan-graham/webapp-express.git

- name: image
  type: docker-image
  source:
    email: {{docker-hub-email}}
    username: dongraham
    password: {{docker-hub-password}}
    repository: dongraham/webapp-express


jobs:
- name: build
  plan:
  - get: src
  - task: build
    file: src/.ci/tasks/build.yml
  - put: image
    params:
      build: build
